all: polynomialtestdriver

polynomialtestdriver: polynomialtest.cpp Polynomial.cpp

	g++ -std=c++11 -g polynomialtest.cpp Polynomial.cpp linkedlist.cpp -o polynomialtestdriver

clean:
	rm polynomialtestdriver